config/routes.rb
Rails.application.routes.draw do
  # Public Namespaced Routes
  namespace :public do
    # Events Routes
    get 'events/new'
    get 'events/create'

    # Group Tags Routes
    resources :group_tags, only: [:show]

    # Homes Routes
    resources :homes, only: [:index]

    # Users Routes
    resources :users, only: [:index, :show, :edit, :update] do
      post 'withdraw', on: :member

      # Shifts Routes
      resources :shifts do
        # カレンダーのシフトを取得するルート
        collection do
          get 'calendar_shifts'
        end
      end
    end

    # Groups Routes
    resources :groups, only: [:index, :show] do
      collection do
        get 'search'  # 検索用ルート
      end
      post 'join', on: :member  # グループ参加用のルート
      delete 'leave', on: :member

      # Events Routes
      resources :events, only: [:new, :create, :show, :index]

      # Group Shifts Routes
      resources :group_shifts
    end

    # Posts Routes
    resources :posts do
      collection do
        get 'search'
      end

      # Post Comments Routes
      resources :post_comments, only: [:create, :destroy]
    end

    # Chats Routes
    resources :chats, only: [:index, :show, :create, :destroy]
  end

  # Admin Namespaced Routes
  namespace :admin do
    # Homes Routes
    resources :homes, only: [:index]  # 管理者用のホーム画面

    # Events Routes
    resources :events, only: [:index, :show]

    # Group Tags Routes
    resources :group_tags

    # Group Shifts Routes
    resources :group_shifts, only: [:index]

    # Shifts Routes
    resources :shifts, only: [:index]

    # Groups Routes
    resources :groups do
      collection do
        get 'search'  # 管理者用検索ルート
      end
      member do
        # グループからユーザーが退会するルートを定義
        delete 'leave/:user_id', to: 'groups#leave', as: 'leave_user'
      end

      # Events Routes for Groups
      resources :events, only: [:index]
    end

    # Users Routes
    resources :users, except: [:new, :create] do
      collection do
        get 'search'  # ユーザー検索機能を追加
      end
    end

    # Post Comments Routes
    resources :post_comments, only: [:index, :destroy] do
      collection do
        get 'search'  # コメント検索機能
      end
    end

    # Posts Routes
    resources :posts, except: [:new, :create] do
      # Post Comments Routes nested
      resources :post_comments, only: [:index, :destroy, :edit, :update]
    end
  end

  # Devise Routes
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :users_guest_sign_in
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # Root Route
  root to: 'homes#top'  # トップページをルートに設定

  # About Route
  get 'about', to: 'homes#about', as: 'about'  # Aboutページのルートを設定
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.order(created_at: :desc).limit(5)  # 新着5件のユーザー
    @active_users = User.where(status: true).order(created_at: :desc).limit(5)  # 新着5件のアクティブユーザー
    @inactive_users = User.where(status: false).order(created_at: :desc).limit(5)  # 新着5件の非アクティブユーザー
    @groups = Group.order(created_at: :desc).limit(5)  # 新着5件のグループ
    @leader_groups = Group.joins(:leader).where(leader_id: User.where(leader: true).pluck(:id)).order(created_at: :desc).limit(5)  # 新着5件のリーダーグループ
    @posts = Post.order(created_at: :desc).limit(5)  # 新着5件の投稿
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/index.html.erb
<div class="container mt-4">
  <h2 class="text-center futuristic-title">管理者ダッシュボード</h2>

  <div class="d-flex flex-wrap justify-content-center mb-4">
  <%= link_to admin_shifts_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fas fa-calendar-check"></i> ユーザーシフト一覧
  <% end %>
  <%= link_to admin_group_shifts_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fas fa-calendar-alt"></i> グループシフト一覧
  <% end %>
  <%= link_to search_admin_users_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fas fa-search"></i> ユーザー検索
  <% end %>
  <%= link_to new_admin_group_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fa-solid fa-users-between-lines"></i></i> グループ作成
  <% end %>
  <%= link_to admin_group_tags_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fas fa-tags"></i> ジョブタグ一覧
  <% end %>
  <%= link_to admin_events_path, class: 'btn btn-outline-primary btn-lg mx-2 mb-2' do %>
    <i class="fas fa-envelope-open-text"></i> 送信済みメール
  <% end %>
  </div>


  <!-- ユーザー一覧リンク -->
  <h3 class="mt-5"><%= link_to 'ユーザー一覧へ', admin_users_path, class: 'nav-link' %></h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>リーダー</th>
        <th>所属グループ</th>
        <th>リーダー状態のグループ</th>
        <th class="text-center">操作</th>
      </tr>
    </thead>
    <tbody>
      <% if @users.present? %>
        <% @users.each do |user| %>
          <tr>
            <td>
            <%= user.name %>
            <% if user.status? %>
            <% else %>
            <span class="required">※退会済み</span>
            <% end %>
            </td>
            <td><%= user.email %></td>
            <td><%= user.leader ? 'リーダー' : '一般ユーザー' %></td>
            <td>
              <% if user.groups.any? %>
                <%= user.groups.map(&:name).join('<br>').html_safe %> <!-- 複数のグループ名を改行して表示 -->
              <% else %>
                未登録
              <% end %>
            </td>
            <td>
              <% leader_groups = Group.where(leader_id: user.id) %>
              <% if leader_groups.any? %>
                <%= leader_groups.map(&:name).join('<br>').html_safe %> <!-- リーダーになっているグループ名を改行して表示 -->
              <% else %>
                なし
              <% end %>
            </td>
            <td class="text-center">
              <%= link_to '詳細', admin_user_path(user), class: 'btn btn-info btn-sm' %>
              <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-warning btn-sm' %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="6" class="text-center">ユーザーが登録されていません。</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- グループ一覧リンク -->
  <h3 class="mt-5"><%= link_to 'グループ一覧へ', admin_groups_path, class: 'nav-link' %></h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>グループ名</th>
        <th>住所</th>
        <th>リーダー</th>
        <th>作成日</th>
        <th class="text-center">操作</th>
      </tr>
    </thead>
    <tbody>
      <% if @groups.present? %>
        <% @groups.each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td><%= group.address %></td>
            <td><%= group.leader.name %></td>
            <td><%= group.created_at.strftime('%Y-%m-%d') %></td>
            <td class="text-center">
              <%= link_to '詳細', admin_group_path(group), class: 'btn btn-info btn-sm' %>
              <%= link_to '編集', edit_admin_group_path(group), class: 'btn btn-warning btn-sm' %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="5" class="text-center">グループが登録されていません。</td>
        </tr>
      <% end %>
    </tbody>
  </table>

<h3 class="mt-5"><%= link_to '投稿一覧へ', admin_posts_path, class: 'nav-link' %></h3>
<% if @posts.any? %>
  <table class="table table-bordered mt-4">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>内容</th>
        <th>投稿者</th>
        <th class="text-center">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= truncate(post.content, length: 50) %></td> <!-- 内容が長い場合は50文字に制限 -->
          <td>
          <%= post.user.name %>
          <% if post.user.status? %>
          <% else %>
          <span class="required">※退会済み</span>
          <% end %>
          </td>
          <td class="text-center">
            <%= link_to '詳細', admin_post_path(post), class: 'btn btn-info btn-sm' %>
            <%= link_to '編集', edit_admin_post_path(post), class: 'btn btn-warning btn-sm' %>
            <%= link_to '削除', admin_post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <div class="alert alert-info text-center" role="alert">
      該当する対象は見つかりませんでした。
    </div>
<% end %>


  <!-- 他のコンテンツ（ユーザー数、グループ数など）-->
  <div class="row futuristic-container mt-5">
    <div class="col-md-4">
      <h4><i class="fas fa-users"></i> ユーザー数: <%= @users.present? ? @users.count : 0 %></h4>
    </div>
    <div class="col-md-4">
      <h4><i class="fas fa-user-check"></i> アクティブユーザー: <%= @active_users.present? ? @active_users.count : 0 %></h4>
    </div>
    <div class="col-md-4">
      <h4><i class="fas fa-users-cog"></i> グループ数: <%= @groups.present? ? @groups.count : 0 %></h4>
    </div>
  </div>

</div>