config/routes.rb
Rails.application.routes.draw do
  # Public Namespaced Routes
  namespace :public do
    # Events Routes
    get 'events/new'
    get 'events/create'

    # Group Tags Routes
    resources :group_tags, only: [:show]

    # Homes Routes
    resources :homes, only: [:index]

    # Users Routes
    resources :users, only: [:index, :show, :edit, :update] do
      post 'withdraw', on: :member

      # Shifts Routes
      resources :shifts do
        # カレンダーのシフトを取得するルート
        collection do
          get 'calendar_shifts'
        end
      end
    end

    # Groups Routes
    resources :groups, only: [:index, :show] do
      collection do
        get 'search'  # 検索用ルート
      end
      post 'join', on: :member  # グループ参加用のルート
      delete 'leave', on: :member

      # Events Routes
      resources :events, only: [:new, :create, :show, :index]

      # Group Shifts Routes
      resources :group_shifts
    end

    # Posts Routes
    resources :posts do
      collection do
        get 'search'
      end

      # Post Comments Routes
      resources :post_comments, only: [:create, :destroy]
    end

    # Chats Routes
    resources :chats, only: [:index, :show, :create, :destroy]
  end

  # Admin Namespaced Routes
  namespace :admin do
    # Homes Routes
    resources :homes, only: [:index]  # 管理者用のホーム画面

    # Events Routes
    resources :events, only: [:index, :show]

    # Group Tags Routes
    resources :group_tags

    # Group Shifts Routes
    resources :group_shifts, only: [:index]

    # Shifts Routes
    resources :shifts, only: [:index]

    # Groups Routes
    resources :groups do
      collection do
        get 'search'  # 管理者用検索ルート
      end
      member do
        # グループからユーザーが退会するルートを定義
        delete 'leave/:user_id', to: 'groups#leave', as: 'leave_user'
      end

      # Events Routes for Groups
      resources :events, only: [:index]
    end

    # Users Routes
    resources :users, except: [:new, :create] do
      collection do
        get 'search'  # ユーザー検索機能を追加
      end
    end

    # Post Comments Routes
    resources :post_comments, only: [:index, :destroy] do
      collection do
        get 'search'  # コメント検索機能
      end
    end

    # Posts Routes
    resources :posts, except: [:new, :create] do
      # Post Comments Routes nested
      resources :post_comments, only: [:index, :destroy, :edit, :update]
    end
  end

  # Devise Routes
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :users_guest_sign_in
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # Root Route
  root to: 'homes#top'  # トップページをルートに設定

  # About Route
  get 'about', to: 'homes#about', as: 'about'  # Aboutページのルートを設定
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :prefecture
  belongs_to :leader, class_name: 'User', foreign_key: :leader_id # リーダーとなるユーザー
  has_many :group_memberships, dependent: :destroy
  has_many :members, through: :group_memberships, source: :user  # メンバーを取得
  has_many :users, through: :group_memberships, source: :user
  has_many :events, dependent: :destroy  # グループに関連するイベントを取得するための関連付け
  has_many :group_tags, dependent: :destroy
  has_many :group_shifts, dependent: :destroy
  accepts_nested_attributes_for :group_tags, allow_destroy: true
  
  validates :name, presence: true
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin! # 管理者の認証
  before_action :set_group, only: [:show, :edit, :update, :destroy, :leave, :destroy]

  # グループ一覧
  def index
    @groups = Group.all
    filter_groups_by_name
    filter_groups_by_prefecture
  end

  def show
    # 詳細ページに表示するための処理
  end

  def edit
    @users = User.where(leader: true)
    @group.group_tags.build if @group.group_tags.empty?
  end

  def update
    if @group.update(group_params)
      redirect_to admin_group_path(@group), notice: 'グループが更新されました。'
    else
      @users = User.where(leader: true)
      @group.group_tags.build if @group.group_tags.empty?
      flash.now[:alert] = 'グループの編集に失敗しました。'
      render :edit
    end
  end

  # グループ作成フォーム
  def new
    @group = Group.new
    @users = User.where(leader: true)
  end

  # グループ作成処理
  def create
    @group = Group.new(group_params)
    if @group.save
      # リーダーをグループに参加させる
      leader = User.find(@group.leader_id)
      membership = GroupMembership.new(user: leader, group: @group)
      if membership.save
        redirect_to admin_groups_path, notice: 'グループが作成され、リーダーを参加させました。'
      else
        # 参加処理が失敗した場合
        flash[:alert] = 'グループは作成されましたが、リーダーの参加に失敗しました。'
        redirect_to admin_groups_path
      end
    else
      @users = User.all
      flash.now[:alert] = @group.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: 'グループが削除されました。'
  end

  # グループ検索
  def search
    @groups = Group.all
    filter_groups_by_name
    filter_groups_by_prefecture
    render :index  # indexビューを再利用
  end

  # 退会アクション
  def leave
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])

    if @group.users.delete(@user)
      redirect_to admin_group_path(@group), notice: "#{@user.name} さんは退会しました。"
    else
      redirect_to admin_group_path(@group), alert: '退会に失敗しました。'
    end
  end

  private

  # ストロングパラメータ
  def group_params
    params.require(:group).permit(:name, :address, :leader_id, :prefecture_id, group_tags_attributes: [:id, :tag_name, :_destroy, :group_id])
  end

  # グループを設定
  def set_group
    @group = Group.find(params[:id]) # グループを取得
  end

  def filter_groups_by_name
    if params[:name].present?
      @groups = @groups.where('name LIKE ?', "%#{params[:name]}%")
    end
  end

  def filter_groups_by_prefecture
    if params[:prefecture_id].present?
      @groups = @groups.where(prefecture_id: params[:prefecture_id])
    end
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/edit.html.erb
<h1 class="my-4 text-center"><%= @group.name %>の編集</h1>

<div class="container">
  <%= form_for([:admin, @group]) do |f| %>
    <div class="card shadow-lg">
      <div class="card-body">
        <div class="form-group mb-3">
          <%= f.label :name, "グループ名", class: 'form-label' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :prefecture_id, '都道府県' %>
          <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: '都道府県を選択してください' %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :address, "住所", class: 'form-label' %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :leader_id, "リーダー", class: 'form-label' %>
          <%= f.collection_select :leader_id, @users, :id, :name, prompt: "リーダーを選択", class: "form-select" %>
        </div>

        <h3>タグ入力</h3>
        <div id="tags">
          <%= f.fields_for :group_tags do |tag_form| %>
            <div class="tag-fields">
              <%= tag_form.label :tag_name, 'タグ名' %>
              <%= tag_form.text_field :tag_name, class: 'form-control' %>
              <%= tag_form.check_box :_destroy %>
              <%= tag_form.label :_destroy, '削除' %>
            </div>
          <% end %>
        </div>

        <%= link_to 'タグを追加', '#', id: 'add_tag', class: 'btn btn-secondary' %>
      </div>
    </div>

    <div class="d-flex justify-content-between">
      <div>
        <%= f.submit '更新', class: 'btn btn-primary mt-3' %>
      </div>
  <% end %>
      <div>
        <%= link_to '削除', admin_group_path(@group), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger mt-3" %>
     </div>
      <div>
        <%= link_to '戻る', request.referer || admin_group_path(@group), class: 'btn btn-secondary mt-3' %>
      </div>
    </div>

</div>

<script>
  document.getElementById('add_tag').addEventListener('click', function(event) {
    event.preventDefault();
    const tagsDiv = document.getElementById('tags');
    const newTagIndex = tagsDiv.querySelectorAll('.tag-fields').length;
    
    const newTagFields = `
      <div class="tag-fields">
        <label for="group_group_tags_attributes_${newTagIndex}_tag_name">タグ名</label>
        <input type="text" name="group[group_tags_attributes][${newTagIndex}][tag_name]" id="group_group_tags_attributes_${newTagIndex}_tag_name" class="form-control">
        <input type="hidden" name="group[group_tags_attributes][${newTagIndex}][_destroy]" id="group_group_tags_attributes_${newTagIndex}__destroy" value="false">
      </div>
    `;
    
    tagsDiv.insertAdjacentHTML('beforeend', newTagFields);
  });
</script>

app/views/admin/groups/index.html.erb
<h1 class="my-4 text-center">管理者用: グループ一覧</h1>

<div class="container">
  <!-- 検索フォーム -->
  <%= form_with url: search_admin_groups_path, method: :get, local: true do %>
    <div class="form-group">
      <%= label_tag :name, 'グループ名検索', class: 'form-label' %>
      <%= text_field_tag :name, params[:name], class: 'form-control', placeholder: 'グループ名を入力' %>
    </div>

    <div class="form-group">
      <%= label_tag :prefecture_id, '都道府県検索', class: 'form-label' %>
      <%= select_tag :prefecture_id, options_from_collection_for_select(Prefecture.all, :id, :name, params[:prefecture_id]), prompt: '選択無し', class: 'form-control' %>
    </div>

    <%= submit_tag '検索', class: 'btn btn-primary' %>
  <% end %>


  <!-- 検索結果一覧 -->
  <% if @groups.any? %>
    <ul class="list-group mt-4">
      <% @groups.each do |group| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <strong>グループ名:</strong> <%= group.name %><br>
            <strong>住所:</strong> <%= group.address %><br>
            <strong>都道府県:</strong> <%= group.prefecture.name %>
          </div>
          <%= link_to '詳細を見る', admin_group_path(group), class: 'btn btn-primary' %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="mt-3">該当するグループは見つかりませんでした。</p>
  <% end %>


  <div class="text-end">
    <%= link_to 'ダッシュボードへ戻る', admin_homes_path, class: 'btn btn-secondary mt-3' %>
  </div>

</div>

app/views/admin/groups/new.html.erb
<h1 class="my-4 text-center">グループ作成</h1>

<div class="container">
  <%= form_with model: @group, url: admin_groups_path, local: true do |f| %>
    <div class="card shadow-lg">
      <div class="card-body">
        <div class="field mb-3">
          <%= f.label :name, "グループ名", class: 'form-label' %>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>

        <div class="field mb-3">
          <%= f.label :address, "住所", class: 'form-label' %>
          <%= f.text_field :address, class: 'form-control', required: true %>
        </div>

        <div class="field mb-3">
          <%= f.label :prefecture_id, '都道府県' %>
          <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: '都道府県を選択してください' %>
        </div>

        <div class="field mb-3">
          <%= f.label :leader_id, "リーダーを選択", class: 'form-label' %>
          <%= f.collection_select :leader_id, @users, :id, :name, prompt: "リーダーを選択", class: 'form-select' %>
        </div>


        <h3>タグ入力</h3>
        <div id="tags">
        <%= f.fields_for :group_tags do |tag_form| %>
          <div class="tag-fields">
            <%= tag_form.label :tag_name, 'タグ名' %>
            <%= tag_form.text_field :tag_name, class: 'form-control' %>
            <%= tag_form.hidden_field :group_id, value: @group.id %>  <!-- ここでグループIDを隠しフィールドとして追加 -->
            <%= tag_form.check_box :_destroy %>
            <%= tag_form.label :_destroy, '削除' %>
          </div>
        <% end %>
        </div>

        <%= link_to 'タグを追加', '#', id: 'add_tag', class: 'btn btn-secondary' %>

      </div>
    </div>

  <div class="d-flex justify-content-between">
    <div class="actions">
      <%= f.submit "作成", class: 'btn btn-primary mt-3' %>
    </div>
  <% end %>
    <div>
      <%= link_to 'ダッシュボードへ戻る', admin_homes_path, class: 'btn btn-secondary mt-3' %> 
    </div>
  </div>
</div>


<script>
  document.getElementById('add_tag').addEventListener('click', function(event) {
    event.preventDefault();
    const tagsDiv = document.getElementById('tags');
    const newTagIndex = tagsDiv.querySelectorAll('.tag-fields').length;
    
    const newTagFields = `
      <div class="tag-fields">
        <label for="group_group_tags_attributes_${newTagIndex}_tag_name">タグ名</label>
        <input type="text" name="group[group_tags_attributes][${newTagIndex}][tag_name]" id="group_group_tags_attributes_${newTagIndex}_tag_name" class="form-control">
        <input type="hidden" name="group[group_tags_attributes][${newTagIndex}][_destroy]" id="group_group_tags_attributes_${newTagIndex}__destroy" value="false">
      </div>
    `;
    
    tagsDiv.insertAdjacentHTML('beforeend', newTagFields);
  });
</script>

app/views/admin/groups/show.html.erb
<div class="container mt-4">
  <!-- グループ詳細カード -->
  <div class="card shadow-lg">
    <div class="card-header text-center">
      <h1 class="card-title"><%= @group.name %> の詳細</h1>
    </div>
    
    <div class="card-body">
      <!-- グループ詳細情報 -->
      <table class="table table-bordered">
        <tr>
          <th>グループ名</th>
          <td><%= @group.name %></td>
        </tr>
        <tr>
          <th>都道府県</th>
          <td><%= @group.prefecture.name %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @group.address %></td>
        </tr>
        <tr>
          <th>リーダー</th>
          <td><%= @group.leader.name %></td>
        </tr>
        <tr>
          <th>タグ</th>
          <td>
            <% if @group.group_tags.any? %>
              <% @group.group_tags.each do |tag| %>
                <%= link_to tag.tag_name, admin_group_tag_path(tag), class: 'btn btn-outline-primary btn-sm' %>
                <% if !@group.group_tags.last.eql?(tag) %> <% end %>
              <% end %>
            <% else %>
              <p>タグはまだありません。</p>
            <% end %>
          </td>
        </tr>
      </table>

      <!-- 参加者一覧の表示 -->
      <% if @group.users.any? %>
        <div class="d-flex justify-content-between">
          <button class="btn btn-info" id="toggle-participants-btn">参加者を表示</button>
          <%= link_to 'イベント一覧', admin_group_events_path(@group), class: 'btn btn-info' %>
        </div>
        
        <div id="participants-list" style="display:none;">
          <table class="table table-striped mt-3">
            <thead>
              <tr>
                <th>名前</th>
                <th>メールアドレス</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <% @group.users.each do |user| %>
                <tr>
                <td>
                  <%= link_to user.name, admin_user_path(user), class: 'btn btn-outline-primary' %>
                  <% if user.status? %>
                <% else %>
                  <span class="required">※退会済み</span>
                <% end %>
                </td>
                  <td><%= user.email %></td>
                  <td>
                    <%= link_to '退会', leave_user_admin_group_path(@group, user), method: :delete, data: { confirm: '管理者では入会させることはできないので取り消しは困難ですが退会させますか' }, class: 'btn btn-warning btn-sm' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p>参加者はまだいません。</p>
      <% end %>
    </div>

    <!-- 編集・戻るボタン -->
    <div class="card-footer d-flex justify-content-between">
      <%= link_to '編集', edit_admin_group_path(@group), class: 'btn btn-warning btn-sm' %>
      <%= link_to '一覧へ戻る', admin_groups_path, class: 'btn btn-secondary btn-sm' %>
    </div>
  </div>
</div>

<!-- トグルボタンのJavaScript -->
<script>
  document.getElementById('toggle-participants-btn').addEventListener('click', function() {
    var participantsList = document.getElementById('participants-list');
    if (participantsList.style.display === "none") {
      participantsList.style.display = "block";
      this.textContent = "参加者を非表示";
    } else {
      participantsList.style.display = "none";
      this.textContent = "参加者を表示";
    }
  });
</script>