config/routes.rb
Rails.application.routes.draw do
  # Public Namespaced Routes
  namespace :public do
    # Events Routes
    get 'events/new'
    get 'events/create'

    # Group Tags Routes
    resources :group_tags, only: [:show]

    # Homes Routes
    resources :homes, only: [:index]

    # Users Routes
    resources :users, only: [:index, :show, :edit, :update] do
      post 'withdraw', on: :member

      # Shifts Routes
      resources :shifts do
        # カレンダーのシフトを取得するルート
        collection do
          get 'calendar_shifts'
        end
      end
    end

    # Groups Routes
    resources :groups, only: [:index, :show] do
      collection do
        get 'search'  # 検索用ルート
      end
      post 'join', on: :member  # グループ参加用のルート
      delete 'leave', on: :member

      # Events Routes
      resources :events, only: [:new, :create, :show, :index]

      # Group Shifts Routes
      resources :group_shifts
    end

    # Posts Routes
    resources :posts do
      collection do
        get 'search'
      end

      # Post Comments Routes
      resources :post_comments, only: [:create, :destroy]
    end

    # Chats Routes
    resources :chats, only: [:index, :show, :create, :destroy]
  end

  # Admin Namespaced Routes
  namespace :admin do
    # Homes Routes
    resources :homes, only: [:index]  # 管理者用のホーム画面

    # Events Routes
    resources :events, only: [:index, :show]

    # Group Tags Routes
    resources :group_tags

    # Group Shifts Routes
    resources :group_shifts, only: [:index]

    # Shifts Routes
    resources :shifts, only: [:index]

    # Groups Routes
    resources :groups do
      collection do
        get 'search'  # 管理者用検索ルート
      end
      member do
        # グループからユーザーが退会するルートを定義
        delete 'leave/:user_id', to: 'groups#leave', as: 'leave_user'
      end

      # Events Routes for Groups
      resources :events, only: [:index]
    end

    # Users Routes
    resources :users, except: [:new, :create] do
      collection do
        get 'search'  # ユーザー検索機能を追加
      end
    end

    # Post Comments Routes
    resources :post_comments, only: [:index, :destroy] do
      collection do
        get 'search'  # コメント検索機能
      end
    end

    # Posts Routes
    resources :posts, except: [:new, :create] do
      # Post Comments Routes nested
      resources :post_comments, only: [:index, :destroy, :edit, :update]
    end
  end

  # Devise Routes
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :users_guest_sign_in
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # Root Route
  root to: 'homes#top'  # トップページをルートに設定

  # About Route
  get 'about', to: 'homes#about', as: 'about'  # Aboutページのルートを設定
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white py-4 mt-5">
  <div class="container text-center">
    <p class="mb-0">&copy; 2024 Share-shift. All rights reserved.</p>
    <div class="mt-3">
      <a href="#" class="text-white me-3">プライバシーポリシー</a>
      <a href="#" class="text-white me-3">利用規約</a>
      <a href="#" class="text-white">お問い合わせ</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <% if admin_signed_in? %>
      <a class="navbar-brand" href="<%= admin_homes_path %>">Share-shift</a>
      <% else %>
        <a class="navbar-brand" href="<%= user_signed_in? ? public_homes_path : root_path %>">Share-shift</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
        <% if admin_signed_in? %>
        <% else %>
          <% if user_signed_in? %>
          <% else %>
              <li class="nav-item">
                <%= link_to 'トップページ', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'About', about_path, class: 'nav-link' %>
              </li>
            <% end %>
          <% end %>
        <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to 'グループ一覧', admin_groups_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', admin_posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ', public_user_path(current_user.id), class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'ユーザー一覧', public_users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'グループ一覧', public_groups_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', public_posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to '新規会員登録', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
            </li>
            <div class="nav-item">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: 'nav-link', method: :post %>
          </div>
          <% end %>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d0cea1656a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      html, body {
        height: 100%;
        margin: 0;
      }

      .content {
        min-height: 100%;
        padding-bottom: 50px;
      }

      footer {
        position: relative;
        bottom: 0;
        width: 100%;
        background-color: #333;
        color: white;
        text-align: center;
        padding: 20px 0;
      }

      /* フラッシュメッセージのスタイル */
      .flash-container {
        position: fixed;
        top: 60px;
        left: 20px; /* 左側に固定 */
        z-index: 1000;
      }

      .flash-message {
        margin: 5px 0;
        padding: 10px 15px;
        border-radius: 5px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        font-size: 14px;
        display: flex;
        align-items: center;
        gap: 8px;
        width: 300px; /* メッセージの横幅を固定 */
      }

      .flash-alert {
        background-color: #f8d7da;
        color: #721c24;
        border-left: 5px solid #f5c6cb;
      }

      .flash-notice {
        background-color: #d4edda;
        color: #155724;
        border-left: 5px solid #c3e6cb;
      }

      .flash-icon {
        font-size: 16px;
      }


      .required {
        color: red;
        font-weight: bold;
      }



    </style>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <!-- フラッシュメッセージ表示 -->
    <div class="flash-container">
      <% if flash[:alert] %>
        <div class="flash-message flash-alert">
          <i class="fas fa-exclamation-circle flash-icon"></i>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div class="flash-message flash-notice">
          <i class="fas fa-check-circle flash-icon"></i>
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>

    <div class="content">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>